<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Municipality;
use App\Models\Secretaria;
use Illuminate\Database\Seeder;

class MunicipalitySeeder extends Seeder
{
    public function run(): void
    {
        $data = $this->getMunicipalitiesData();

        foreach ($data as $item) {
            $department = Department::where('name', $item['department'])->first();
            $secretaria = Secretaria::where('name', $item['secretaria'])->first();

            if (!$department || !$secretaria) {
                continue;
            }

            Municipality::create([
                'name' => $item['municipality'],
                'dane_code' => $item['dane_code'],
                'department_id' => $department->id,
                'secretaria_id' => $secretaria->id,
            ]);
        }
    }

    private function getMunicipalitiesData(): array
    {
        return [
            ['department' => 'ANTIOQUIA', 'secretaria' => 'MEDELLIN', 'dane_code' => '5001', 'municipality' => 'MEDELLÍN'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'BELLO', 'dane_code' => '5088', 'municipality' => 'BELLO'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'LA ESTRELLA', 'dane_code' => '5380', 'municipality' => 'LA ESTRELLA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'SABANETA', 'dane_code' => '5631', 'municipality' => 'SABANETA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5030', 'municipality' => 'AMAGÁ'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5036', 'municipality' => 'ANGELÓPOLIS'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5129', 'municipality' => 'CALDAS'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ENVIGADO', 'dane_code' => '5266', 'municipality' => 'ENVIGADO'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ITAGUI', 'dane_code' => '5360', 'municipality' => 'ITAGÜÍ'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5809', 'municipality' => 'TITIRIBÍ'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5154', 'municipality' => 'CAUCASIA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5250', 'municipality' => 'EL BAGRE'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5895', 'municipality' => 'ZARAGOZA'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23079', 'municipality' => 'BUENAVISTA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5120', 'municipality' => 'CÁCERES'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5495', 'municipality' => 'NECHÍ'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23350', 'municipality' => 'LA APARTADA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5079', 'municipality' => 'BARBOSA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5585', 'municipality' => 'PUERTO NARE'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5579', 'municipality' => 'PUERTO BERRÍO'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5591', 'municipality' => 'PUERTO TRIUNFO'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5670', 'municipality' => 'SAN ROQUE'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5893', 'municipality' => 'YONDÓ'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5690', 'municipality' => 'SANTO DOMINGO'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5031', 'municipality' => 'AMALFI'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5040', 'municipality' => 'ANORÍ'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5212', 'municipality' => 'COPACABANA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5308', 'municipality' => 'GIRARDOTA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5361', 'municipality' => 'ITUANGO'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5686', 'municipality' => 'SANTA ROSA DE OSOS'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5887', 'municipality' => 'YARUMAL'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5604', 'municipality' => 'REMEDIOS'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5042', 'municipality' => 'SANTA FÉ DE ANTIOQUIA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5138', 'municipality' => 'CAÑASGORDAS'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5234', 'municipality' => 'DABEIBA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5480', 'municipality' => 'MUTATÁ'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5543', 'municipality' => 'PEQUE'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5656', 'municipality' => 'SAN JERÓNIMO'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5284', 'municipality' => 'FRONTINO'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5055', 'municipality' => 'ARGELIA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5148', 'municipality' => 'EL CARMEN DE VIBORAL'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5197', 'municipality' => 'COCORNÁ'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5318', 'municipality' => 'GUARNE'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5376', 'municipality' => 'LA CEJA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5440', 'municipality' => 'MARINILLA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'RIONEGRO', 'dane_code' => '5615', 'municipality' => 'RIONEGRO'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5697', 'municipality' => 'EL SANTUARIO'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5093', 'municipality' => 'BETULIA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5101', 'municipality' => 'CIUDAD BOLÍVAR'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5364', 'municipality' => 'JARDÍN'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5642', 'municipality' => 'SALGAR'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5789', 'municipality' => 'TÁMESIS'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5034', 'municipality' => 'ANDES'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5390', 'municipality' => 'LA PINTADA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5847', 'municipality' => 'URRAO'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5051', 'municipality' => 'ARBOLETES'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5665', 'municipality' => 'SAN PEDRO DE URABÁ'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'TURBO', 'dane_code' => '5837', 'municipality' => 'TURBO'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5659', 'municipality' => 'SAN JUAN DE URABÁ'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5490', 'municipality' => 'NECOCLÍ'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'APARTADO', 'dane_code' => '5045', 'municipality' => 'APARTADÓ'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5147', 'municipality' => 'CAREPA'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5172', 'municipality' => 'CHIGORODÓ'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'MONTERIA', 'dane_code' => '23001', 'municipality' => 'MONTERÍA'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23807', 'municipality' => 'TIERRALTA'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23855', 'municipality' => 'VALENCIA'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23419', 'municipality' => 'LOS CÓRDOBAS'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23500', 'municipality' => 'MOÑITOS'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23672', 'municipality' => 'SAN ANTERO'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23675', 'municipality' => 'SAN BERNARDO DEL VIENTO'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23090', 'municipality' => 'CANALETE'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23574', 'municipality' => 'PUERTO ESCONDIDO'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23182', 'municipality' => 'CHINÚ'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'LORICA', 'dane_code' => '23417', 'municipality' => 'LORICA'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23586', 'municipality' => 'PURÍSIMA DE LA CONCEPCIÓN'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'SAHAGUN', 'dane_code' => '23660', 'municipality' => 'SAHAGÚN'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23670', 'municipality' => 'SAN ANDRÉS DE SOTAVENTO'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23464', 'municipality' => 'MOMIL'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23815', 'municipality' => 'TUCHÍN'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23068', 'municipality' => 'AYAPEL'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23466', 'municipality' => 'MONTELÍBANO'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23570', 'municipality' => 'PUEBLO NUEVO'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23580', 'municipality' => 'PUERTO LIBERTADOR'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23682', 'municipality' => 'SAN JOSÉ DE URÉ'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23555', 'municipality' => 'PLANETA RICA'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23162', 'municipality' => 'CERETÉ'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23189', 'municipality' => 'CIÉNAGA DE ORO'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23686', 'municipality' => 'SAN PELAYO'],
            ['department' => 'CÓRDOBA', 'secretaria' => 'CORDOBA', 'dane_code' => '23300', 'municipality' => 'COTORRA'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27006', 'municipality' => 'ACANDÍ'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27615', 'municipality' => 'RIOSUCIO'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27493', 'municipality' => 'NUEVO BELÉN DE BAJIRÁ'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27800', 'municipality' => 'UNGUÍA'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27150', 'municipality' => 'CARMEN DEL DARIÉN'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27075', 'municipality' => 'BAHÍA SOLANO'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27077', 'municipality' => 'BAJO BAUDÓ'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27495', 'municipality' => 'NUQUÍ'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27025', 'municipality' => 'ALTO BAUDÓ'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27430', 'municipality' => 'MEDIO BAUDÓ'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27372', 'municipality' => 'JURADÓ'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5475', 'municipality' => 'MURINDÓ'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27099', 'municipality' => 'BOJAYÁ'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27787', 'municipality' => 'TADÓ'],
            ['department' => 'ANTIOQUIA', 'secretaria' => 'ANTIOQUIA', 'dane_code' => '5873', 'municipality' => 'VIGÍA DEL FUERTE'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27413', 'municipality' => 'LLORÓ'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27001', 'municipality' => 'QUIBDÓ'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27600', 'municipality' => 'RÍO QUITO'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27425', 'municipality' => 'MEDIO ATRATO'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27073', 'municipality' => 'BAGADÓ'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27135', 'municipality' => 'EL CANTÓN DEL SAN PABLO'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27245', 'municipality' => 'EL CARMEN DE ATRATO'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27050', 'municipality' => 'ATRATO'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27160', 'municipality' => 'CÉRTEGUI'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27810', 'municipality' => 'UNIÓN PANAMERICANA'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27205', 'municipality' => 'CONDOTO'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27660', 'municipality' => 'SAN JOSÉ DEL PALMAR'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27580', 'municipality' => 'RÍO IRÓ'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27450', 'municipality' => 'MEDIO SAN JUAN'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27491', 'municipality' => 'NÓVITA'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27361', 'municipality' => 'ISTMINA'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27250', 'municipality' => 'EL LITORAL DEL SAN JUAN'],
            ['department' => 'CHOCÓ', 'secretaria' => 'CHOCO', 'dane_code' => '27745', 'municipality' => 'SIPÍ'],
            ['department' => 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA', 'secretaria' => 'SAN ANDRES', 'dane_code' => '88001', 'municipality' => 'SAN ANDRÉS'],
            ['department' => 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA', 'secretaria' => 'SAN ANDRES', 'dane_code' => '88564', 'municipality' => 'PROVIDENCIA'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70221', 'municipality' => 'COVEÑAS'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70820', 'municipality' => 'SANTIAGO DE TOLÚ'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70713', 'municipality' => 'SAN ONOFRE'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70823', 'municipality' => 'TOLÚ VIEJO'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70523', 'municipality' => 'PALMITO'],
            ['department' => 'SUCRE', 'secretaria' => 'SINCELEJO', 'dane_code' => '70001', 'municipality' => 'SINCELEJO'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70670', 'municipality' => 'SAMPUÉS'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70215', 'municipality' => 'COROZAL'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70235', 'municipality' => 'GALERAS'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70742', 'municipality' => 'SAN LUIS DE SINCÉ'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70473', 'municipality' => 'MORROA'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70702', 'municipality' => 'SAN JUAN DE BETULIA'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70204', 'municipality' => 'COLOSÓ'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70230', 'municipality' => 'CHALÁN'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70418', 'municipality' => 'LOS PALMITOS'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70508', 'municipality' => 'OVEJAS'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70717', 'municipality' => 'SAN PEDRO'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70429', 'municipality' => 'MAJAGUAL'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70708', 'municipality' => 'SAN MARCOS'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70265', 'municipality' => 'GUARANDA'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70678', 'municipality' => 'SAN BENITO ABAD'],
            ['department' => 'SUCRE', 'secretaria' => 'SUCRE', 'dane_code' => '70771', 'municipality' => 'SUCRE'],
        ];
    }
}
